FROM varnish:6.0.11

COPY ./docker/varnish/default.vcl /etc/varnish/default.vcl

COPY ./docker/varnish/entrypoint.sh /var/entrypoint.sh
RUN chmod +x /var/entrypoint.sh

ENTRYPOINT [ "/var/entrypoint.sh" ]
CMD ["/usr/local/bin/docker-varnish-entrypoint"]