version: "3.2"

services:
    thumbor:
        image: minimalcompact/thumbor
        environment:
          - THUMBOR_NUM_PROCESSES=4
          - SECURITY_KEY=ALAMAKOTA
          - ALLOW_UNSAFE_URL=False
          - RESULT_STORAGE=thumbor.result_storages.no_storage
          - AUTO_WEBP=True
        deploy:
            placement:
                constraints:
                    - node.role == worker
    varnish:
        image: thumbor-varnish
        environment:
          - VARNISH_SIZE=2G 
        deploy:
            placement:
                constraints:
                    - node.role == manager
        ports:
            - "8080:80"