version: '3'
services:
  thumbor:
    image: minimalcompact/thumbor
    # config: https://thumbor.readthedocs.io/en/latest/configuration.html
    environment:
      - THUMBOR_NUM_PROCESSES=4
      - SECURITY_KEY=ALAMAKOTA
      - ALLOW_UNSAFE_URL=False
      - RESULT_STORAGE=thumbor.result_storages.no_storage
      - AUTO_WEBP=True
  varnish:
    build:
      context: ./
      dockerfile: ./docker/varnish/dockerfile
    ports:
      - "8080:80"
    tmpfs:
      - /var/lib/varnish/varnishd:exec
    environment:
      - VARNISH_SIZE=2G  