version: '3'
services:
  thumbor:
    build:
      context: ./
      dockerfile: ./docker/thumbor/dockerfile
    image: minimalcompact/thumbor
    env_file:
      - ./docker/thumbor/.env
  varnish:
    build:
      context: ./
      dockerfile: ./docker/varnish/dockerfile
    env_file:
      - ./docker/varnish/.env      
    ports:
      - "8080:80"
    tmpfs:
      - /var/lib/varnish/varnishd:exec